In [156]:
import requests
from bs4 import BeautifulSoup

In [157]:
# browser_headers = {'User Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0'}
# URL = 'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(500)
# text = requests.get(URL, headers= browser_headers).text
# print(text)
def webScrape_pageList(numberOfPages):
  browser_headers = {'User Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0'}
  page_content = []
  for i in range(numberOfPages):
    URL = 'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i+1)
    page_content.append(requests.get(URL, headers= browser_headers).text)
  return page_content
def webScrape_pageSingle(pageNo):
  browser_headers = {'User Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0'}
  page_content = []
  URL = 'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(pageNo)
  page_content.append(requests.get(URL, headers= browser_headers).text)
  return page_content

In [158]:
contents = webScrape_pageList(500)
content = webScrape_pageSingle(482)

In [159]:
# Creating an BeautifulSoup object for the beautification and easy retrieval
def printAllPages(contents):
  for i in range(len(contents)):
    bsObj = BeautifulSoup(contents[i], 'lxml') # lxml is the parser
    print("--------------")
    print(bsObj.prettify())
    print("--------------")
def printSinglePage(content):
  bsObj = BeautifulSoup(content[0], 'lxml') # lxml is the parser
  print("--------------")
  print(bsObj.prettify())
  print("--------------")

In [160]:
# printAllPages(contents)
len(contents)

500

In [161]:
# printSinglePage(content)

In [162]:
import json
import pandas as pd

In [163]:
contentDictList =[]
for i in range(len(contents)):
  # print('++++++++++++')
  # print(contents[i])
  # print('++++++++++++')
  bsObj = BeautifulSoup(contents[i], 'lxml') # lxml is the parser
  # print(bsObj.prettify())
  # print(f"at {i} value = {type(bsObj.find('p'))}")
  # print (str(type(bsObj.find('p'))) != "<class 'NoneType'>")
  if (str(type(bsObj.find('p'))) != "<class 'NoneType'>"):
    json_text = bsObj.find('p').get_text(strip= True)
    contentDict = json.loads(json_text)
    contentDictList.append(contentDict)

print(contentDictList[482]['results'])
print(len(contentDictList[482]['results']))

[{'adult': False, 'backdrop_path': '/e0fWkS9iJkLV2jSZ5g2MF2iTIKS.jpg', 'genre_ids': [35, 10749], 'id': 19824, 'original_language': 'en', 'original_title': 'Van Wilder: Freshman Year', 'overview': 'It is freshman year at Coolidge College and Van Wilder is ready to party. To his dismay, all the girls have taken a vow of chastity and the dean rules the school. Van embarks on a crusade to land the campus hottie, Kaitlin, and liberate his school from sexual oppression and party dysfunction.', 'popularity': 2.3467, 'poster_path': '/tjDH8REu8bqgW9zXDIOy6C8FNtH.jpg', 'release_date': '2009-06-02', 'title': 'Van Wilder: Freshman Year', 'video': False, 'vote_average': 5.431, 'vote_count': 333}, {'adult': False, 'backdrop_path': '/nWtvOG4zXhtpXoIlJB4wZp8DShi.jpg', 'genre_ids': [28, 12, 27, 53], 'id': 9042, 'original_language': 'en', 'original_title': 'The Cave', 'overview': 'After a group of biologists discovers a huge network of unexplored caves in Romania and, believing it to be an undisturbed eco-system that has produced a new species, they hire the best American team of underwater cave explorers in the world. While exploring deeper into the underwater caves, a rockslide blocks their exit, and they soon discover a larger carnivorous creature has added them to its food chain.', 'popularity': 4.6474, 'poster_path': '/q7eyZY2Akj68ivnRZ86OduCUexy.jpg', 'release_date': '2005-08-26', 'title': 'The Cave', 'video': False, 'vote_average': 5.4, 'vote_count': 977}, {'adult': False, 'backdrop_path': '/eo1yKDfZioYBlAzw8XwHQhZF34J.jpg', 'genre_ids': [28, 12, 35, 10751], 'id': 14560, 'original_language': 'en', 'original_title': 'Paul Blart: Mall Cop', 'overview': 'Mild-mannered Paul Blart has always had huge dreams of becoming a State Trooper. Until then, he patrols the local mall as a security guard. With his closely cropped moustache, personal transporter and gung-ho attitude, only Blart seems to take his job seriously. All that changes when a team of thugs raids the mall and takes hostages. Untrained, unarmed and a super-size target, Blart has to become a real cop to save the day.', 'popularity': 4.2544, 'poster_path': '/A4zZv0Q1VKURFZFEl2vwjaE2q0g.jpg', 'release_date': '2009-01-15', 'title': 'Paul Blart: Mall Cop', 'video': False, 'vote_average': 5.4, 'vote_count': 2597}, {'adult': False, 'backdrop_path': '/gkkBhctHPGg8hrmtWbO3ySZoj4z.jpg', 'genre_ids': [18, 53], 'id': 453201, 'original_language': 'en', 'original_title': 'The 15:17 to Paris', 'overview': "On Aug. 21, 2015, the world watches in stunned silence as the media reports a thwarted terrorist attack on a train that's bound for Paris -- an attempt prevented by three young Americans traveling together through Europe. The heroic and courageous actions of Anthony Sadler, Alek Skarlatos and Spencer Stone help to save the lives of more than 500 passengers on board.", 'popularity': 2.1227, 'poster_path': '/3NtkRNmvMrQIOtyWTaOKVNJyP1W.jpg', 'release_date': '2018-02-07', 'title': 'The 15:17 to Paris', 'video': False, 'vote_average': 5.428, 'vote_count': 1635}, {'adult': False, 'backdrop_path': '/v5C8SDi6nGYI0dLbegvTyrU581p.jpg', 'genre_ids': [10749, 18], 'id': 323674, 'original_language': 'en', 'original_title': '6 Years', 'overview': 'A young couple bound by a seemingly ideal love, begins to unravel as unexpected opportunities spin them down a volatile and violent path and threaten the future they had always imagined.', 'popularity': 1.2499, 'poster_path': '/dE9kVpWI2F5jI8LGWby5t7iFwXe.jpg', 'release_date': '2015-03-14', 'title': '6 Years', 'video': False, 'vote_average': 5.428, 'vote_count': 715}, {'adult': False, 'backdrop_path': '/e29oMyfzzlWbhRlCBrzmZhlsw2m.jpg', 'genre_ids': [28, 12, 878], 'id': 121856, 'original_language': 'en', 'original_title': "Assassin's Creed", 'overview': 'Through a technology that unlocks the generic memories of his ancestor in 15th century Spain, Callum Lynch discovers he is a descendant of an ancient line of Assassins and amasses lethal skills to take on the oppressive Templar Order.', 'popularity': 7.4649, 'poster_path': '/ne5LmY2zq2dTG8TDGJOrCB4IbRy.jpg', 'release_date': '2016-12-21', 'title': "Assassin's Creed", 'video': False, 'vote_average': 5.428, 'vote_count': 7897}, {'adult': False, 'backdrop_path': '/jlRT2jOhmKLAKrV1cu3VgpLfw9u.jpg', 'genre_ids': [28, 35, 878, 14], 'id': 9067, 'original_language': 'en', 'original_title': 'Tank Girl', 'overview': "After a comet disrupts the rain cycle of Earth, the planet has become a desolate, barren desert by the year 2033. With resources scarce, Kesslee, head of the powerful and evil Water & Power Corporation, the de facto government, has taken control of the water supply. Unwilling to cower under Kesslee's tyrannical rule, a pair of outlaws known as Tank Girl and Jet Girl rise up, joining the mysterious rebel Rippers to destroy the corrupt system.", 'popularity': 2.0151, 'poster_path': '/qohdY3BcJ98sFneOUAWp0FmH4Z6.jpg', 'release_date': '1995-03-31', 'title': 'Tank Girl', 'video': False, 'vote_average': 5.427, 'vote_count': 531}, {'adult': False, 'backdrop_path': '/c4sKPgyJj19GBCAvUjpPRiiA45.jpg', 'genre_ids': [35, 53], 'id': 276839, 'original_language': 'en', 'original_title': 'Home Sweet Hell', 'overview': 'Don Champagne seems to have it all, but when his wife, Mona, learns of his affair with a pretty new salesgirl, she will stop at nothing to maintain their storybook life.', 'popularity': 1.5149, 'poster_path': '/a0S1ou77hJ8RAxGkpyZGbfUr2SG.jpg', 'release_date': '2015-03-13', 'title': 'Home Sweet Hell', 'video': False, 'vote_average': 5.426, 'vote_count': 466}, {'adult': False, 'backdrop_path': '/hCaxuZ4VGXBUh2fdvCtyqhh4C9n.jpg', 'genre_ids': [18, 80], 'id': 96936, 'original_language': 'en', 'original_title': 'The Bling Ring', 'overview': "Inspired by actual events, a group of fame-obsessed teenagers use the Internet to track celebrities' whereabouts in order to rob their homes.", 'popularity': 5.0138, 'poster_path': '/eQHniJoGUSU5ULABwYX9P3k2LC3.jpg', 'release_date': '2013-06-12', 'title': 'The Bling Ring', 'video': False, 'vote_average': 5.426, 'vote_count': 3066}, {'adult': False, 'backdrop_path': '/6Uh1OQOJEvjCs3XOLJoGAnKEUhr.jpg', 'genre_ids': [18, 12, 14, 878, 10752], 'id': 530081, 'original_language': 'en', 'original_title': 'The Man Who Killed Hitler and Then the Bigfoot', 'overview': 'Decades after serving in WWII and assassinating Adolf Hitler, a legendary American war veteran must now hunt down the fabled Bigfoot.', 'popularity': 0.7861, 'poster_path': '/kQNeWBT1VqtSMtgfEn3zFjRogyH.jpg', 'release_date': '2019-02-08', 'title': 'The Man Who Killed Hitler and Then the Bigfoot', 'video': False, 'vote_average': 5.425, 'vote_count': 454}, {'adult': False, 'backdrop_path': '/lhGLPatKPAKmtBzUbXiz8Foi5zZ.jpg', 'genre_ids': [28, 12, 14, 27, 878, 53], 'id': 10336, 'original_language': 'en', 'original_title': 'Spawn', 'overview': "After being murdered by corrupt colleagues in a covert government agency, Al Simmons makes a pact with the devil to be resurrected to see his beloved wife Wanda. In exchange for his return to Earth, Simmons agrees to lead Hell's Army in the destruction of mankind.", 'popularity': 3.6307, 'poster_path': '/3svvunKXkhRvEKByGDua1Qu0otq.jpg', 'release_date': '1997-07-31', 'title': 'Spawn', 'video': False, 'vote_average': 5.425, 'vote_count': 1407}, {'adult': False, 'backdrop_path': '/uGmYqxh8flqkudioyFtD7IJSHxK.jpg', 'genre_ids': [18, 80, 53], 'id': 889737, 'original_language': 'en', 'original_title': 'Joker: Folie à Deux', 'overview': "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.", 'popularity': 13.6916, 'poster_path': '/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg', 'release_date': '2024-10-01', 'title': 'Joker: Folie à Deux', 'video': False, 'vote_average': 5.425, 'vote_count': 2567}, {'adult': False, 'backdrop_path': '/8HfjrSxfTVKmjNh8cJjbu5eXzcX.jpg', 'genre_ids': [10751, 14, 28, 12], 'id': 420808, 'original_language': 'en', 'original_title': 'Peter Pan & Wendy', 'overview': 'Wendy Darling, a young girl afraid to leave her childhood home behind, meets Peter Pan, a boy who refuses to grow up. Alongside her brothers and a tiny fairy, Tinker Bell, she travels with Peter to the magical world of Neverland. There, she encounters an evil pirate captain, Captain Hook, and embarks on a thrilling adventure that will change her life forever.', 'popularity': 10.2775, 'poster_path': '/9NXAlFEE7WDssbXSMgdacsUD58Y.jpg', 'release_date': '2023-04-20', 'title': 'Peter Pan & Wendy', 'video': False, 'vote_average': 5.4, 'vote_count': 726}, {'adult': False, 'backdrop_path': '/uiFvf7rKju8Zd7kTqpKzFjaRvZ2.jpg', 'genre_ids': [14, 35, 28, 12, 10749, 878], 'id': 10658, 'original_language': 'en', 'original_title': 'Howard the Duck', 'overview': "A scientific experiment unknowingly brings extraterrestrial life forms to the Earth through a laser beam. First is the cigar-smoking drake, Howard, from the duck's planet. A few kids try to keep him from the greedy scientists and help him back to his planet, but then a much less friendly being arrives through the beam...", 'popularity': 5.5544, 'poster_path': '/eU0dWo8PJgsSAZFbcyHiUpuLSyW.jpg', 'release_date': '1986-08-01', 'title': 'Howard the Duck', 'video': False, 'vote_average': 5.424, 'vote_count': 1061}, {'adult': False, 'backdrop_path': '/qu0HXKZBsugBiHJm4QZdFiSrvPi.jpg', 'genre_ids': [878, 12], 'id': 2157, 'original_language': 'en', 'original_title': 'Lost in Space', 'overview': 'The prospects for continuing life on Earth in the year 2058 are grim. So the Robinsons are launched into space to colonize Alpha Prime, the only other inhabitable planet in the galaxy. But when a stowaway sabotages the mission, the Robinsons find themselves hurtling through uncharted space.', 'popularity': 5.0134, 'poster_path': '/fCocPDUFuKswY2GxDdfYsT9BXMd.jpg', 'release_date': '1998-04-03', 'title': 'Lost in Space', 'video': False, 'vote_average': 5.424, 'vote_count': 1254}, {'adult': False, 'backdrop_path': '/o2iN9n2ShVqobqnYR0odM6yIlgW.jpg', 'genre_ids': [53, 27], 'id': 203834, 'original_language': 'en', 'original_title': 'Jessabelle', 'overview': "A young woman recuperating at her father's run-down home after a tragic accident soon encounters a terrifying presence with a connection to her long-deceased mother.", 'popularity': 1.8159, 'poster_path': '/oyszsO25OfSxkxhKCCnk9ZrAjkp.jpg', 'release_date': '2014-11-07', 'title': 'Jessabelle', 'video': False, 'vote_average': 5.423, 'vote_count': 816}, {'adult': False, 'backdrop_path': '/rzTw6K1TbmF8qCUHWFrGhgXkBp5.jpg', 'genre_ids': [35, 10749, 10751], 'id': 38317, 'original_language': 'en', 'original_title': 'Zookeeper', 'overview': "Kindhearted Griffin Keyes is one of the best-loved caretakers at the Franklin Park Zoo, but he's more comfortable with the animals than with females of his own species as proven by his failed marriage proposal to the self-absorbed Stephanie several years ago. The animals have listened to Griffin pine over her for years and, after she reappears in his life, they decide to help Griffin rekindle the relationship and become the alpha male she wants him to be. They inadvertently reveal their secret ability to talk and, after Griffin's initial shock, teach him the rules of courtship, animal-style. Surprisingly, the animals' advice really works and Griffin is about to get everything he's ever dreamed of--or is he?", 'popularity': 3.8655, 'poster_path': '/y3b4AYw8dr4hIKTfEAjxUxx0z8G.jpg', 'release_date': '2011-07-06', 'title': 'Zookeeper', 'video': False, 'vote_average': 5.423, 'vote_count': 1712}, {'adult': False, 'backdrop_path': '/ftVld1YSBU92swRb1mRryUs7xR2.jpg', 'genre_ids': [35], 'id': 516043, 'original_language': 'it', 'original_title': 'Arrivano i prof', 'overview': "The Manzoni High School in Milan is the worst in Italy. When the percentage of those promoted falls to 12%, it's time for the last resort: to entrust the classes to the worst of the available teachers.", 'popularity': 3.6365, 'poster_path': '/mBc8UOa5VxdgLfY5qYWZvuboJKq.jpg', 'release_date': '2018-05-01', 'title': 'Here Come the Teachers', 'video': False, 'vote_average': 5.422, 'vote_count': 386}, {'adult': False, 'backdrop_path': '/kReEky4XRCAq22H5V37kDcNY9dj.jpg', 'genre_ids': [53, 18], 'id': 500904, 'original_language': 'en', 'original_title': 'A Vigilante', 'overview': 'A once-abused woman devotes herself to ridding victims of their domestic abusers while hunting down the one she must kill to be truly free.', 'popularity': 1.249, 'poster_path': '/avoKZfgBzyBGJsrAr2WQOwZK978.jpg', 'release_date': '2019-03-29', 'title': 'A Vigilante', 'video': False, 'vote_average': 5.422, 'vote_count': 391}, {'adult': False, 'backdrop_path': '/lj7enxOyRXazcCIFJyCn9dLuF2V.jpg', 'genre_ids': [35, 80, 9648], 'id': 338964, 'original_language': 'en', 'original_title': 'Bad Santa 2', 'overview': "Fueled by cheap whiskey, greed and hatred, Willie Soke teams up with his angry little sidekick, Marcus, to knock off a Chicago charity on Christmas Eve. Along for the ride is chubby and cheery Thurman Merman, a 250-pound ray of sunshine who brings out Willie's sliver of humanity. Issues arise when the pair are joined by Willie's horror story of a mother, who raises the bar for the gang's ambitions, while somehow lowering the standards of criminal behavior.", 'popularity': 2.575, 'poster_path': '/xmsEwpA2fSq6IO3sfKrLuIPLHSc.jpg', 'release_date': '2016-11-23', 'title': 'Bad Santa 2', 'video': False, 'vote_average': 5.4, 'vote_count': 823}]
20

In [164]:
contentDictList =[]
for i in range(len(contents)):
  # print('++++++++++++')
  # print(contents[i])
  # print('++++++++++++')
  bsObj = BeautifulSoup(contents[i], 'lxml') # lxml is the parser
  # print(bsObj.prettify())
  # print(f"at {i} value = {type(bsObj.find('p'))}")
  # print (str(type(bsObj.find('p'))) != "<class 'NoneType'>")
  if (str(type(bsObj.find('p'))) != "<class 'NoneType'>"):
    json_text = bsObj.find('p').get_text(strip= True)
    contentDict = json.loads(json_text)
    contentDictList.append(contentDict)

adult = []
genre_ids = []
original_language = []
original_title = []
overview = []
popularity = []
release_date = []
title = []
vote_average = []
vote_count = []
for content in contentDictList:
  for item in content['results']:
    adult.append(item['adult'])
    genre_ids.append(item['genre_ids'])
    original_language.append(item['original_language'])
    original_title.append(item['original_title'])
    overview.append(item['overview'])
    popularity.append(item['popularity'])
    release_date.append(item['release_date'])
    title.append(item['title'])
    vote_average.append(item['vote_average'])
    vote_count.append(item['vote_count'])

d = {'adult':adult, 'genre_ids':genre_ids, 'original_language':original_language, 'overview':overview, 'popularity':popularity, 'release_date':release_date, 'title':title, 'vote_average':vote_average, 'vote_count':vote_count}
df = pd.DataFrame(d)
len(df)
df.head()

,adult,genre_ids,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,False,"[18, 80]",en,Imprisoned in the 1940s for the double murder ...,27.5968,1994-09-23,The Shawshank Redemption,8.712,28814
1,False,"[18, 80]",en,"Spanning the years 1945 to 1955, a chronicle o...",28.3575,1972-03-14,The Godfather,8.700,21785
2,False,"[18, 80]",en,In the continuing saga of the Corleone crime f...,17.1099,1974-12-20,The Godfather Part II,8.571,13159
3,False,"[18, 36, 10752]",en,The true story of how businessman Oskar Schind...,18.1267,1993-12-15,Schindler's List,8.565,16675
4,False,[18],en,The defense and the prosecution have rested an...,12.2818,1957-04-10,12 Angry Men,8.500,9362

In [166]:
df.to_csv("/content/drive/MyDrive/WebScrapedCSVs/movies.csv", index=False)

In [167]:
dfNew = pd.read_csv("/content/drive/MyDrive/WebScrapedCSVs/movies.csv")

In [168]:
dfNew

,adult,genre_ids,original_language,overview,popularity,release_date,title,vote_average,vote_count
0,False,"[18, 80]",en,Imprisoned in the 1940s for the double murder ...,27.5968,1994-09-23,The Shawshank Redemption,8.712,28814
1,False,"[18, 80]",en,"Spanning the years 1945 to 1955, a chronicle o...",28.3575,1972-03-14,The Godfather,8.700,21785
2,False,"[18, 80]",en,In the continuing saga of the Corleone crime f...,17.1099,1974-12-20,The Godfather Part II,8.571,13159
3,False,"[18, 36, 10752]",en,The true story of how businessman Oskar Schind...,18.1267,1993-12-15,Schindler's List,8.565,16675
4,False,[18],en,The defense and the prosecution have rested an...,12.2818,1957-04-10,12 Angry Men,8.500,9362
...,...,...,...,...,...,...,...,...,...
9975,False,[27],en,A suburban teen girl and her little brother mu...,2.2118,2022-10-10,Grimcutty,5.123,395
9976,False,"[28, 878, 27]",en,After a virus of epic proportions overwhelms t...,1.4217,2016-02-26,Pandemic,5.100,363
9977,False,"[28, 12]",en,A mysterious warrior teams up with the daughte...,1.8238,2014-09-26,Outcast,5.123,489
9978,False,"[18, 80, 53]",en,Carved from a lifetime of experience that runs...,1.3300,2016-11-04,Dog Eat Dog,5.122,362
9979,False,"[10749, 35]",en,18-year-old Jenny Taylor is ecstatic when she ...,1.5806,2005-11-01,Love Wrecked,5.120,508